version: '3.3'
services:
  app:
    image: 'davyj0nes/k8s-example-app:latest'
    ports:
      - '8080:8080'
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/etc/:/etc/prometheus/'
  grafana:
    image: grafana/grafana:master
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=openup
    ports:
      - '3001:3000'
    volumes:
      - './grafana/lib:/var/lib/grafana'
      - './grafana/etc:/var/etc/grafana'
