apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-example-app
  labels:
    app: k8s-example-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s-example-app
    spec:
      containers:
        - name: k8s-example-app
          image: 'docker.io/davyj0nes/k8s-example-app:.Release'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      terminationGracePeriodSeconds: 30
