apiVersion: v1
kind: Service
metadata:
  name: k8s-example-app
  labels:
    app: k8s-example-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: k8s-example-app
  type: LoadBalancer
